# Generated by Django 6.0.5 on 2026-06-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usersubscription_images_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identification',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
