# Generated by Django 6.0.5 on 2026-06-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='businesses_deleted',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
