# Generated by Django 6.0.5 on 2026-06-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usersubscription_businesses_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='identification',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
