# Generated by Django 6.0.5 on 2026-06-02 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('ia', '0002_generatedpost_is_favorite_generatedpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedpost',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.businessprofile'),
        ),
    ]
