# Generated by Django 6.0.5 on 2026-06-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0003_generatedpost_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedpost',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('tiktok', 'TikTok')], max_length=20),
        ),
    ]
