# Generated by Django 6.0.5 on 2026-06-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0004_alter_generatedpost_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedpost',
            name='generated_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='generatedpost',
            name='image_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='generatedpost',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp')], max_length=20),
        ),
    ]
