# Generated by Django 6.0.5 on 2026-06-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0005_generatedpost_generated_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedpost',
            name='generated_image_url',
        ),
        migrations.RemoveField(
            model_name='generatedpost',
            name='image_prompt',
        ),
    ]
