# Generated by Django 6.0.5 on 2026-06-07 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0006_remove_generatedpost_generated_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedpost',
            name='photo_idea',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('image_url', models.URLField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ia.generatedpost')),
            ],
        ),
    ]
