# Generated by Django 6.0.5 on 2026-06-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0007_generatedpost_photo_idea_generatedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='generated_images/'),
        ),
    ]
