# Generated by Django 6.0.5 on 2026-06-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0008_remove_generatedimage_image_url_generatedimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedpost',
            name='friendly_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedpost',
            name='funny_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedpost',
            name='professional_text',
            field=models.TextField(blank=True),
        ),
    ]
