# Generated by Django 6.0.5 on 2026-06-17 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0009_generatedpost_friendly_text_generatedpost_funny_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='generated_posters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='ia.generatedpost')),
            ],
        ),
    ]
