# Generated by Django 6.0.5 on 2026-06-24 20:36

from django.db import migrations

def seed_business_types(apps, schema_editor):
    BusinessType = apps.get_model('ia', 'BusinessType')

    default_types = [
        "Restaurante",
        "Heladería",
        "Cafetería",
        "Boutique",
        "Floristería",
        "Pastelería",
        "Emprendimiento",
        "Servicios",
    ]

    for name in default_types:
        BusinessType.objects.get_or_create(name=name)



class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0011_seed_business_types'),
    ]

    operations = [
        migrations.RunPython(seed_business_types),
    ]
